# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-26 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birtday',
            new_name='birthday',
        ),
    ]
