# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-26 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playerapp', '0002_auto_20171226_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='writer',
        ),
        migrations.AddField(
            model_name='song',
            name='writer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='writer', to='playerapp.Artist'),
            preserve_default=False,
        ),
    ]
